name: Docker Build Image

on:
  push:
    branches:
      - main


jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t fastapi-image -f src/Dockerfile .

      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name fastapi_container fastapi-image

      - name: List Running Containers
        run: docker ps

      - name: Check Container Status
        run: |
          if [ "$(docker inspect -f '{{.State.Running}}' fastapi_container)" != "true" ]; then
            echo "Container is not running"
            exit 1
          fi

      - name: Wait for API to Start
        run: sleep 5

      - name: Making curl request to default endpoint
        run: curl -f http://localhost:8000/home

